import Head from "next/head";
import HeroSection from "../components/HeroSection/HeroSection";
import Layout from "../components/Layouts/Layout";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <HeroSection />
      </Layout>
    </div>
  );
}
